#!/usr/bin/env bash
# Script to install nginx web server 

apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
ufw allow ssh
ufw allow 'OpenSSH'
echo "Holberton School for the win!" | tee /var/www/html/index.html
service nginx start
