#!/usr/bin/env bash
# Script to install nginx web server 

apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
ufw allow ssh
ufw allow 'OpenSSH'
echo "Holberton School for the win!" | tee /var/www/html/index.html
sed -i "30i \\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default
sudo service nginx restart
