#!/usr/bin/env bash
# Script for the not found page 404

apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
ufw allow ssh
ufw allow 'OpenSSH'
echo "Holberton School for the win!" | tee /var/www/html/index.html
sed -i "30i \\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/no_found_404.html
sudo sed -i "31i \\ \\ error_page 404 /no_found_404.html;\n \\ \\ location = /no_found_404.html { \n \\ \\ root /usr/share/nginx/html;\n \\ \\ internal;\n \\ } " /etc/nginx/sites-available/default
sudo sed -i "19i \\ \\ add_header X-Served-By '1210-web-02'; " /etc/nginx/sites-available/default
sudo service nginx restart