#!/usr/bin/env bash
# bash script that does the backup all db and then compressed it

mysqldump --user=root --password=$1 --all-databases > backup.sql
name_file=$(date +"%d-%m-%Y")
sudo tar -cvzf "$name_file.tar.gz" backup.sql
