#!/usr/bin/env bash
# This script is displaying FizzBuzz

counter=1
while ((counter<101))
do
    if (("$counter"%3==0 && "$counter"%5==0))
    then
	echo "FizzBuzz"
    elif(("$counter"%3==0))
    then
	echo "Fizz"
    elif(("$counter"%5==0))
    then
	echo "Buzz"
    else
	echo "$counter"
    fi
    (( counter++ ))
done
