#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times

counter=1
while ((counter<21))
do
    case $counter in
	4) echo "$counter"
	   echo "bad luck from China"
	   ;;
	9) echo "$counter"
	   echo "bad luck from Japan"
	   ;;
	17) echo "$counter"
	    echo "bad luck from Italy"
	    ;;
	*) echo "$counter"
    esac
    (( counter++ ))
done
