#!/usr/bin/env bash
# This script is displays the time for 12 hours and 59 minutes

hour=0
minute=1

while ((hour<13))
do
    echo "Hour: $hour"
    minute=1
    while((minute<60))
    do
	echo "$minute"
	(( minute++ ))
    done
    (( hour++ ))
done
