#!/usr/bin/env bash
# Bash script that gives you information about the holbertonschool file

file="holbertonschool"

if [ -e "$file" ]
then
echo "holbertonschool file exists"

if [ -s "$file" ]
then
echo "holbertonschool file is not empty"
else
echo "holbertonschool file is empty"
fi

if [ -f "$file" ]
then
echo "holbertonschool is a regular file"
fi
# else
# echo "holbertonschool file is empty"
else
echo "holbertonschool file does not exist"
# elif(("$counter"==8))
# then
# echo "good luck"
# else
# echo "Holberton School"
# fi
# (( counter++ ))
fi




# if ((-e "holbertonschool"))
# then
# echo "holbertonschool file exists"
# elif(("$counter"==8))
# then
# echo "good luck"
# else
# echo "Holberton School"
# fi
# (( counter++ ))